spring:
  profiles:
    active: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: maximo
    password: maximo

---
spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@10.10.11.172:1521:orcl

---
spring:
  profiles: local
  datasource:
    url: jdbc:oracle:thin:@centos-local:1521:orcl

