spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: maximo
    password: maximo
  jpa:
    show-sql: false
server:
  port: 9999
logging:
  level:
    root: info




---
spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@10.10.11.172:1521:orcl

---
spring:
  profiles: local
  datasource:
    url: jdbc:oracle:thin:@centos-linux:1521:orcl

